apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/rollout-restart/base?ref=v0.3

resources:
  - git-task.yaml
  - create-pr-task.yaml
  - tag-and-push-image-task.yaml
  - generate-id-task.yaml
  - dotnet-sdk-task.yaml
  - dotnet-sdk-sonar-task.yaml
  - kustomize-task.yaml

