kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    tenant: contoso
    argocd.applicaion/type: namespace
    namespace.env: cicd
  name: contoso-cicd
spec:
  destination:
    namespace: contoso-cicd
    server: https://kubernetes.default.svc
  project: contoso-namespaces
  source:
    path: 01-namespaces/contoso-cicd
    repoURL: https://github.com/pittar-gitops/gitops-tenant-contoso.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true