kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: developer-gitops

bases:
  # List of Projects for this tenant in this cluster.
  - ../../../02-namespaces/contoso-cicd
  - ../../../02-namespaces/contoso-dev
  - ../../../02-namespaces/contoso-test
  - ../../../02-namespaces/contoso-prod

resources:
  - projects-project.yaml